from Bio import Align
import re
aligner = Align.PairwiseAligner(match_score=1.0)
prot1 = "HPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRIDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPVAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW"
prot2 = "KELNDLEKKYNAHIGVYALDTKSGKEVKFNSDKRFAYASTSKAINSAILLEQVPYNKLNKKVHINKDDIVAYSPILEKYVGKDITLKALIEASMTYSDNTANNKIIKEIGGIKKVKQRLKELGDKVTNPVRYQIELDYYSPKSKKDTSTPAAFGKTLNKLIANGKLSKENKKFLLDLMLNNKSGDTLIKDGVPKDYKVADKSGQAITYASRNDVAFVYPKGQSEPIVLVIFTNKDNKSDKPNDKLISETAKSVMKEF"
alignments = aligner.align(prot1,prot2)
str1 = "S45 S105 S210 G211 R218"
str2 = "S39 S97 K201 S202 G203"
str1 = re.findall(r'[0-9]{1,4}',str1)
str2 = re.findall(r'[0-9]{1,4}', str2)

for alignment in alignments:
      
      print(alignment)
      print(prot1[27:30] , prot2[22:25])
      tupleAlign = alignment.aligned
      print(tupleAlign[1])
  
      for i in str1:
            print(str(prot1[int(i)-1]),end=' ')
      print('')
      for i in str2:
            print(str(prot2[int(i)-1]), end=' ')
      print('')
      
      
      break


# S45 S105 S210 G211 R218
# S39 S97 K201 S202 G203
#